
# Env default values
REDIS_URL = "redis://localhost:6379/0"
CONTAINER_POOL_SIZE = 5

DOCKER_SOCKET = "unix://var/run/docker.sock"

NGINX_BRIDGE_NAME = "nginx-bridge"
NGINX_BRIDGE_PORT = 8000
NGINX_BRIDGE_HOSTNAME = "nginx-bridge"
NGINX_BRIDGE_USERNAME = "username"
NGINX_BRIDGE_PASSWORD = "password"

CHALLENGE_PHP_CONTAINER_NAME="challenge3-php-"
CHALLENGE_PHP_CONTAINER_IMAGE="challenge3-php"
CHALLENGE_REDIS_CONTAINER_NAME="challenge3-redis-"
CHALLENGE_REDIS_CONTAINER_IMAGE="challenge3-redis"
CHALLENGE_NETWORK_NAME="challenge3-net-"


# Env name
ENV_NAME_REDIS = "REDIS_URL"
ENV_NAME_SECRET_KEY = "SECRET_KEY"

ENV_NAME_CONTAINER_POOL_SIZE = "CONTAINER_POOL_SIZE"

ENV_NAME_DOCKER_SOCKET = "DOCKER_SOCKET"

ENV_NAME_NGINX_BRIDGE_HOSTNAME = "NGINX_BRIDGE_HOSTNAME"
ENV_NAME_NGINX_BRIDGE_PORT  = "NGINX_BRIDGE_PORT"
ENV_NAME_NGINX_BRIDGE_USERNAME = "NGINX_BRIDGE_USERNAME"
ENV_NAME_NGINX_BRIDGE_PASSWORD = "NGINX_BRIDGE_PASSWORD"

ENV_NAME_CONTAINER_NGINX_BRIDGE = "NGINX_BRIDGE_NAME"
ENV_NAME_CHALLENGE_CONTAINER_NAME_PHP = "CHALLENGE_PHP_CONTAINER_NAME"
ENV_NAME_CHALLENGE_CONTAINER_IMAGE_PHP = "CHALLENGE_PHP_CONTAINER_IMAGE"
ENV_NAME_CHALLENGE_CONTAINER_NAME_REDIS = "CHALLENGE_REDIS_CONTAINER_NAME"
ENV_NAME_CHALLENGE_CONTAINER_IMAGE_REDIS = "CHALLENGE_REDIS_CONTAINER_IMAGE"
ENV_NAME_CHALLENGE_NETWORK = "CHALLENGE_NETWORK_NAME"
